package main

type country struct {
	Name string
	Code string
}

var countries = map[string]string{
	"Afghanistan":                       "af",
	"Ägypten":                           "eg",
	"Albanien":                          "al",
	"Algerien":                          "dz",
	"Andorra":                           "ad",
	"Angola":                            "ao",
	"Antigua und Barbuda":               "ag",
	"Äquatorialguinea":                  "gq",
	"Argentinien":                       "ar",
	"Armenien":                          "am",
	"Aserbaidschan":                     "az",
	"Äthiopien":                         "et",
	"Australien":                        "au",
	"Bahamas":                           "bs",
	"Bahrain":                           "bh",
	"Bangladesch":                       "bd",
	"Barbados":                          "bb",
	"Belgien":                           "be",
	"Belize":                            "bz",
	"Benin":                             "bj",
	"Bhutan":                            "bt",
	"Bolivien":                          "bo",
	"Bosnien und Herzegowina":           "ba",
	"Botsuana":                          "bw",
	"Brasilien":                         "br",
	"Brunei Darussalam":                 "bn",
	"Bulgarien":                         "bg",
	"Burkina Faso":                      "bf",
	"Burundi":                           "bi",
	"Cayman-Inseln":                     "ky",
	"Chile":                             "cl",
	"China":                             "cn",
	"Cookinseln":                        "ck",
	"Costa Rica":                        "cr",
	"Dänemark":                          "dk",
	"Deutschland":                       "de",
	"Republik Kongo":                    "cd",
	"Dominica":                          "dm",
	"Dominikanische Republik":           "do",
	"Dschibuti":                         "dj",
	"Ecuador":                           "ec",
	"El Salvador":                       "sv",
	"Elfenbeinküste":                    "ci",
	"Eritrea":                           "er",
	"Estland":                           "ee",
	"Fidschi":                           "fj",
	"Finnland":                          "fi",
	"Frankreich":                        "fr",
	"Gabun":                             "ga",
	"Gambia":                            "gm",
	"Georgien":                          "ge",
	"Ghana":                             "gh",
	"Grenada":                           "gd",
	"Griechenland":                      "gr",
	"Großbritannien":                    "gb",
	"Guatemala":                         "gt",
	"Guinea":                            "gn",
	"Guinea-Bissau":                     "gw",
	"Guyana":                            "gy",
	"Haiti":                             "ht",
	"Honduras":                          "hn",
	"Indien":                            "in",
	"Indonesien":                        "id",
	"Irak":                              "iq",
	"Iran":                              "ir",
	"Irland":                            "ie",
	"Island":                            "is",
	"Israel":                            "il",
	"Italien":                           "it",
	"Jamaika":                           "jm",
	"Japan":                             "jp",
	"Jemen":                             "ye",
	"Jordanien":                         "jo",
	"Kambodscha":                        "kh",
	"Kamerun":                           "cm",
	"Kanada":                            "ca",
	"Kap Verde":                         "cv",
	"Kasachstan":                        "kz",
	"Katar":                             "qa",
	"Kenia":                             "ke",
	"Kirgisistan":                       "kg",
	"Kiribati":                          "ki",
	"Kolumbien":                         "co",
	"Komoren":                           "km",
	"Kongo":                             "cg",
	"Kongo, Dem.Rep.":                   "cd",
	"Kroatien":                          "hr",
	"Kuba":                              "cu",
	"Kuwait":                            "kw",
	"Laos":                              "la",
	"Lesotho":                           "ls",
	"Lettland":                          "lv",
	"Libanon":                           "lb",
	"Liberia":                           "lr",
	"Libyen":                            "ly",
	"Liechtenstein":                     "li",
	"Litauen":                           "lt",
	"Luxemburg":                         "lu",
	"Madagaskar":                        "mg",
	"Malawi":                            "mw",
	"Malaysia":                          "my",
	"Malediven":                         "mv",
	"Mali":                              "ml",
	"Malta":                             "mt",
	"Marokko":                           "ma",
	"Marshallinseln":                    "mh",
	"Mauretanien":                       "mr",
	"Mauritius":                         "mu",
	"Mazedonien":                        "mk",
	"Mexiko":                            "mx",
	"Mikronesien":                       "fm",
	"Moldau":                            "md",
	"Monaco":                            "mc",
	"Mongolei":                          "mn",
	"Montenegro":                        "me",
	"Mosambik":                          "mz",
	"Myanmar":                           "mm",
	"Namibia":                           "na",
	"Nauru":                             "nr",
	"Nepal":                             "np",
	"Neuseeland":                        "nz",
	"Nicaragua":                         "ni",
	"Niederlande":                       "nl",
	"Niger":                             "ne",
	"Nigeria":                           "ng",
	"Nordkorea":                         "kp",
	"Norwegen":                          "no",
	"Oman":                              "om",
	"Österreich":                        "at",
	"Timor-Leste":                       "tl",
	"Pakistan":                          "pk",
	"Palästinensische Autonomiegebiete": "ps",
	"Palau":                          "pw",
	"Panama":                         "pa",
	"Papua Neuguinea":                "pg",
	"Paraguay":                       "py",
	"Peru":                           "pe",
	"Philippinen":                    "ph",
	"Polen":                          "pl",
	"Portugal":                       "pt",
	"Ruanda":                         "rw",
	"Rumänien":                       "ro",
	"Russland":                       "ru",
	"Russische Föderation":           "ru",
	"Salomonen":                      "sb",
	"Sambia":                         "zm",
	"Samoa":                          "ws",
	"San Marino":                     "sm",
	"Sao Tome und Principe":          "st",
	"Saudiarabien":                   "sa",
	"Schweden":                       "se",
	"Schweiz":                        "ch",
	"Senegal":                        "sn",
	"Serbien":                        "rs",
	"Seychellen":                     "sc",
	"Sierra Leone":                   "sl",
	"Simbabwe":                       "zw",
	"Singapur":                       "sg",
	"Slowakei":                       "sk",
	"Slowenien":                      "si",
	"Somalia":                        "so",
	"Spanien":                        "es",
	"Sri Lanka":                      "lk",
	"St. Kitts und Nevis":            "kn",
	"St. Lucia":                      "lc",
	"St. Vincent und die Grenadinen": "vc",
	"Südafrika":                      "za",
	"Sudan":                          "sd",
	"Südkorea":                       "kr",
	"Suriname":                       "sr",
	"Swasiland":                      "sz",
	"Syrien":                         "sy",
	"Tadschikistan":                  "tj",
	"Taiwan":                         "tw",
	"Tansania":                       "tz",
	"Thailand":                       "th",
	"Togo":                           "tg",
	"Tonga":                          "to",
	"Trinidad und Tobago":            "tt",
	"Tschad":                         "td",
	"Tschechische Republik":          "cz",
	"Tunesien":                       "tn",
	"Türkei":                         "tr",
	"Turkmenistan":                   "tm",
	"Tuvalu":                         "tv",
	"Uganda":                         "ug",
	"Ukraine":                        "ua",
	"Ungarn":                         "hu",
	"Uruguay":                        "uy",
	"USA":                            "us",
	"Usbekistan":                     "uz",
	"Vanuatu":                        "vu",
	"Vatikan":                        "va",
	"Venezuela":                      "ve",
	"Vereinigte Arabische Emirate":   "ae",
	"Vietnam":                        "vn",
	"Zentralafrikanische Republik":   "cf",
}
