name: Update

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip action')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - name: Run Program
        run: go run -mod=vendor *.go
      - name: Commit Data
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update current data" -a
          git pull origin master --rebase
      - name: Push Data
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
